<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Documentation\**" />
    <Content Remove="Documentation\**" />
    <EmbeddedResource Remove="Documentation\**" />
    <None Remove="Documentation\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DTOs\" />
    <Folder Include="Handlers\" />
    <Folder Include="Extensions\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AIronChef.Application\AIronChef.Application.csproj" />
    <ProjectReference Include="..\AIronChef.Infrastructure\AIronChef.Infrastructure.csproj" />
  </ItemGroup>

</Project>
